export const STATES = {
    INPUT_WALLET_ADDRESS: 'INPUT_WALLET_ADDRESS',
    CHOOSE_WALLET_TYPE: 'CHOOSE_WALLET_TYPE',
    INPUT_CHAIN: 'INPUT_CHAIN',
    INPUT_AIRDROP_LINK: 'INPUT_AIRDROP_LINK',
    INPUT_AIRDROP_TITLE: 'INPUT_AIRDROP_TITLE',
    CHOOSE_AIRDROP_TYPE: 'CHOOSE_AIRDROP_TYPE',
    CHOOSE_WALLET: 'CHOOSE_WALLET',
    CHOOSE_WALLET_DELETE: 'CHOOSE_WALLET_DELETE',
    CHOOSE_AIRDROP_DELETE: 'CHOOSE_AIRDROP_DELETE',
    REMINDER_SETT_MODE: 'REMINDER_SETT_MODE',
    REMINDER_SETT_DELAY: 'REMINDER_SETT_DELAY',
    REMINDER_SETT_CHOOSE: 'REMINDER_SETT_CHOOSE',
    STOP_REMINDER_CHOOSE: 'STOP_REMINDER_CHOOSE'
};

export const COLUMN_WIDTH = 44.2;
export const EXCEL_FILE = 'mydata_data_airdrop.xlsx';
export const WALLET_FILE = 'wallet_address.json';